version: '3'

services:

  nginx:
    image: nginx:1.17.10
    depends_on: 
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8880:8880

  frontend:
    image: frontend
    volumes:
      - ./react_frontend/src:/frontend/src
      - ./react_frontend/public:/frontend/public
      - ./react_frontend/package.json:/package.json
    ports: 
      - 3000:3000

  backend:
    image: backend
    volumes:
      - ./flask_backend:/backend
    restart: on-failure
    ports:
      - 5000:5000